package view;

import comandos.Parser;
import constantes.Constantes;
import controller.*;
import cycling.Ciclista;
import globalInterfaces.ObjetosQueSeEjecutan;
import herramientas.Contenedor;
import herramientas.Logger;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import tiempo.Reloj;

/**
 *
 * Clase que genera el panel de control de la aplicacion
 *
 * @author Raul Cobos y Sergio Rodriguez
 */
public class PanelDeControl extends javax.swing.JFrame implements ObjetosQueSeEjecutan {

    private ArrayList<Ciclista> ciclistas;
    private Parser parser;
    private PanelCarrera panelCarrera;
    private Contenedor contenedor;

    /**
     * Creates new form PanelDeControl
     */
    public PanelDeControl(Contenedor _contenedor, Parser _parser, PanelCarrera _panelCarrera) {

        contenedor = _contenedor;
        ciclistas = contenedor.getListaCiclistas();
        parser = _parser;
        panelCarrera = _panelCarrera;


        initComponents();

        initValores();
        addListeners();



        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBotones = new javax.swing.JPanel();
        jComboBoxIDCiclista = new javax.swing.JComboBox();
        jSpinnerPinones = new javax.swing.JSpinner();
        jSpinnerPlatos = new javax.swing.JSpinner();
        jLabelPlatosTxt = new javax.swing.JLabel();
        jLabelPinonesTxt = new javax.swing.JLabel();
        jLabelCiclistasTxt = new javax.swing.JLabel();
        jSpinnerCadencia = new javax.swing.JSpinner();
        jLabelCadenciaTxt = new javax.swing.JLabel();
        jSpinnerPeriodo = new javax.swing.JSpinner();
        jLabelPeriodoTxt = new javax.swing.JLabel();
        jButtonFrenar = new javax.swing.JButton();
        jSliderIntensidadFrenada = new javax.swing.JSlider();
        jSliderDuracionFrenada = new javax.swing.JSlider();
        jLabelDuracionFrenadaTxt = new javax.swing.JLabel();
        jLabelIntensidadFrenadaTxt = new javax.swing.JLabel();
        jLabelComandosTxt = new javax.swing.JLabel();
        jTextFieldComandos = new javax.swing.JTextField();
        jLabelRelojAplicacion = new javax.swing.JLabel();
        jLabelRelojSistema = new javax.swing.JLabel();
        jLabelRelojAplicacionTxt = new javax.swing.JLabel();
        jLabelRelojSistemaTxt = new javax.swing.JLabel();
        jLabelConfirmacionTxt = new javax.swing.JLabel();
        jPanelIndicadores = new javax.swing.JPanel();
        jLabelVelocidadTxt = new javax.swing.JLabel();
        jLabelVelocidad = new javax.swing.JLabel();
        jLabelPendienteTxt = new javax.swing.JLabel();
        jLabelPendiente = new javax.swing.JLabel();
        jLabelVelocidadVientoTxt = new javax.swing.JLabel();
        jLabelVelocidadViento = new javax.swing.JLabel();
        jLabelFuerzaTxt = new javax.swing.JLabel();
        jLabelFuerza = new javax.swing.JLabel();
        jLabelCiclistaTxt = new javax.swing.JLabel();
        jLabelFactoresTxt = new javax.swing.JLabel();
        jLabelEspacioRecorridoTxt = new javax.swing.JLabel();
        jLabelEspacioRecorrido = new javax.swing.JLabel();
        jPanelLoggin = new javax.swing.JPanel();
        jLabelLogginTxt = new javax.swing.JLabel();
        jScrollPaneLoggin = new javax.swing.JScrollPane();
        jTextAreaLoggin = new javax.swing.JTextArea();
        jScrollPaneCarreraFondo = new javax.swing.JScrollPane();
        jPanelCarreraFondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBotones.setBackground(new java.awt.Color(42, 70, 180));

        jSpinnerPinones.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jSpinnerPlatos.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabelPlatosTxt.setText("Platos");

        jLabelPinonesTxt.setText("Pinones");

        jLabelCiclistasTxt.setText("Ciclistas:");

        jSpinnerCadencia.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jSpinnerCadencia.setModel(new javax.swing.SpinnerNumberModel(0, 0, 120, 5));

        jLabelCadenciaTxt.setText("Cadencia (p/m)");

        jSpinnerPeriodo.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jSpinnerPeriodo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 2.0d, 0.1d));

        jLabelPeriodoTxt.setText("Periodo (s)");

        jButtonFrenar.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jButtonFrenar.setText("Frenar");

        jSliderIntensidadFrenada.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jSliderIntensidadFrenada.setValue(0);

        jSliderDuracionFrenada.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jSliderDuracionFrenada.setMaximum(6);
        jSliderDuracionFrenada.setValue(0);

        jLabelDuracionFrenadaTxt.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabelDuracionFrenadaTxt.setText("Intensidad Frenada(0-100)%");

        jLabelIntensidadFrenadaTxt.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabelIntensidadFrenadaTxt.setText("Duracion Frenada(0-6)s");

        jLabelComandosTxt.setText("Comandos: (\"help\" para ayuda)");

        jTextFieldComandos.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N

        jLabelRelojAplicacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRelojAplicacion.setText("00:00:00:00");

        jLabelRelojSistema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRelojSistema.setText("00:00:00:00");

        jLabelRelojAplicacionTxt.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabelRelojAplicacionTxt.setText("Reloj aplicacion");

        jLabelRelojSistemaTxt.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabelRelojSistemaTxt.setText("Reloj de sistema");

        jLabelConfirmacionTxt.setText("Enter");

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotonesLayout.createSequentialGroup()
                        .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelBotonesLayout.createSequentialGroup()
                                    .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelBotonesLayout.createSequentialGroup()
                                            .addGap(15, 15, 15)
                                            .addComponent(jSpinnerPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelPlatosTxt))
                                    .addGap(59, 59, 59)
                                    .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanelBotonesLayout.createSequentialGroup()
                                            .addComponent(jLabelPinonesTxt)
                                            .addGap(83, 83, 83)
                                            .addComponent(jLabelCadenciaTxt))
                                        .addGroup(jPanelBotonesLayout.createSequentialGroup()
                                            .addComponent(jSpinnerPinones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSpinnerCadencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBotonesLayout.createSequentialGroup()
                                    .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBoxIDCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelRelojAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelRelojAplicacionTxt))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelRelojSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelRelojSistemaTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)))
                            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelComandosTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldComandos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelConfirmacionTxt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPeriodoTxt)
                                    .addComponent(jSliderDuracionFrenada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSliderIntensidadFrenada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))))
                    .addGroup(jPanelBotonesLayout.createSequentialGroup()
                        .addComponent(jLabelCiclistasTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelIntensidadFrenadaTxt))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelDuracionFrenadaTxt)))
                .addContainerGap())
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerPinones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCadencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlatosTxt)
                    .addComponent(jLabelPinonesTxt)
                    .addComponent(jLabelCadenciaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPeriodoTxt))
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBotonesLayout.createSequentialGroup()
                        .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelDuracionFrenadaTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderIntensidadFrenada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelCiclistasTxt)
                                    .addComponent(jLabelIntensidadFrenadaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelRelojSistemaTxt)
                                    .addComponent(jLabelRelojAplicacionTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelRelojSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelRelojAplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)))
                        .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderDuracionFrenada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxIDCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBotonesLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelComandosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldComandos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConfirmacionTxt))
                        .addGap(47, 47, 47)
                        .addComponent(jButtonFrenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );

        jPanelIndicadores.setBackground(new java.awt.Color(146, 105, 42));

        jLabelVelocidadTxt.setText("Velocidad:");

        jLabelVelocidad.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabelVelocidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVelocidad.setText(" 0 Km/h");

        jLabelPendienteTxt.setText("Pendiente:");

        jLabelPendiente.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabelPendiente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPendiente.setText("%");

        jLabelVelocidadVientoTxt.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        jLabelVelocidadVientoTxt.setText("Velocidad Viento:");

        jLabelVelocidadViento.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabelVelocidadViento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVelocidadViento.setText("Km/h");

        jLabelFuerzaTxt.setText("Fuerza:");

        jLabelFuerza.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabelFuerza.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFuerza.setText("100 %");

        jLabelCiclistaTxt.setFont(new java.awt.Font("Cantarell", 3, 18)); // NOI18N
        jLabelCiclistaTxt.setText("Ciclista:");

        jLabelFactoresTxt.setFont(new java.awt.Font("Cantarell", 3, 18)); // NOI18N
        jLabelFactoresTxt.setText("Factores Externos:");

        jLabelEspacioRecorridoTxt.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        jLabelEspacioRecorridoTxt.setText("Espacio Recorrido");

        jLabelEspacioRecorrido.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabelEspacioRecorrido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEspacioRecorrido.setText("0 Km");

        javax.swing.GroupLayout jPanelIndicadoresLayout = new javax.swing.GroupLayout(jPanelIndicadores);
        jPanelIndicadores.setLayout(jPanelIndicadoresLayout);
        jPanelIndicadoresLayout.setHorizontalGroup(
            jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIndicadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIndicadoresLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFuerzaTxt)
                            .addComponent(jLabelVelocidadTxt)
                            .addComponent(jLabelEspacioRecorridoTxt))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelEspacioRecorrido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelFuerza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelVelocidad, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                    .addGroup(jPanelIndicadoresLayout.createSequentialGroup()
                        .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPendienteTxt)
                            .addComponent(jLabelVelocidadVientoTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelVelocidadViento, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jLabelPendiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIndicadoresLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCiclistaTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFactoresTxt, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanelIndicadoresLayout.setVerticalGroup(
            jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIndicadoresLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelCiclistaTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelIndicadoresLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelVelocidadTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFuerza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFuerzaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEspacioRecorridoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEspacioRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelFactoresTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelVelocidadVientoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelVelocidadViento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPendienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabelLogginTxt.setBackground(new java.awt.Color(254, 254, 254));
        jLabelLogginTxt.setFont(new java.awt.Font("Cantarell", 3, 18)); // NOI18N
        jLabelLogginTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogginTxt.setText("Loggin");

        jScrollPaneLoggin.setAutoscrolls(true);
        jScrollPaneLoggin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPaneLoggin.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jScrollPaneLoggin.setNextFocusableComponent(jTextAreaLoggin);

        jTextAreaLoggin.setColumns(20);
        jTextAreaLoggin.setRows(5);
        jScrollPaneLoggin.setViewportView(jTextAreaLoggin);

        javax.swing.GroupLayout jPanelLogginLayout = new javax.swing.GroupLayout(jPanelLoggin);
        jPanelLoggin.setLayout(jPanelLogginLayout);
        jPanelLogginLayout.setHorizontalGroup(
            jPanelLogginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLogginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogginTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLogginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPaneLoggin, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelLogginLayout.setVerticalGroup(
            jPanelLogginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogginLayout.createSequentialGroup()
                .addComponent(jLabelLogginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneLoggin))
        );

        jPanelCarreraFondo.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jPanelCarreraFondo.setLayout(null);
        jScrollPaneCarreraFondo.setViewportView(jPanelCarreraFondo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelIndicadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelLoggin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPaneCarreraFondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelIndicadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLoggin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneCarreraFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Asigna a los diferentes componentes del panel sus valores iniciales
     */
    private void initValores() {


        jSpinnerPinones.setModel(new javax.swing.SpinnerNumberModel(Constantes.PINON_INICIAL, Integer.valueOf(1), (Comparable) Constantes.NUMERO_PINONES, Integer.valueOf(1)));

        jSpinnerPlatos.setModel(new javax.swing.SpinnerNumberModel(Constantes.PLATO_INICIAL, Integer.valueOf(1), (Comparable) Constantes.NUMERO_PLATOS, Integer.valueOf(1)));

        jSpinnerCadencia.setModel(new javax.swing.SpinnerNumberModel(Constantes.CADENCIA_INICIAL, 0, 120, 5));

        jSpinnerPeriodo.setModel(new javax.swing.SpinnerNumberModel(Constantes.TIEMPO_POR_PEDALADA, 0.0d, 2.0d, 0.1d));

        for (int i = 0; i < Constantes.NUMERO_CICLISTAS; i++) {
            jComboBoxIDCiclista.addItem("Ciclista[" + i + "]");

            /**
             * ImageIcon icon = new ImageIcon("img/bici" + i + ".png");
             * jPanelCarreraFondo.add(new JLabel(icon));
             * jPanelCarreraFondo.getComponent(i).setSize(20, 16);
             * jPanelCarreraFondo.getComponent(i).setVisible(true);
             */
        }

        ImageIcon img = new ImageIcon("img/meta.png");

        jPanelCarreraFondo.add(new JLabel(img));
        jPanelCarreraFondo.getComponent(0).setSize(50, 100);
        jPanelCarreraFondo.getComponent(0).setVisible(true);

        for (int i = 1; i < contenedor.getCurvas().getNumCurvas() + 1; i++) {

            img = new ImageIcon("img/curve.gif");
            jPanelCarreraFondo.add(new JLabel(img));
            jPanelCarreraFondo.getComponent(i).setSize(20, 17);
            jPanelCarreraFondo.getComponent(i).setVisible(true);
        }
    }

    /**
     * Delega la accion de los actionperformed de los botones del panel en el
     * controlador, quien será quien implemente la accion una vez mande el
     * evento el componente
     */
    private void addListeners() {

        jSpinnerPeriodo.addChangeListener(new PeriodoListener(ciclistas, this));
        jSpinnerCadencia.addChangeListener(new CadenciaListener(ciclistas, this));
        jSpinnerPinones.addChangeListener(new PinonListener(ciclistas, this));
        jSpinnerPlatos.addChangeListener(new PlatoListener(ciclistas, this));

        jButtonFrenar.addActionListener(new FrenarListener(ciclistas, this));

        jComboBoxIDCiclista.addActionListener(new IDListener(ciclistas, this));
        jTextFieldComandos.addActionListener(new CampoComandosListener(parser, this));

    }

    public void mostrarPanelGanador(int id) {
        Graphics g = jPanelCarreraFondo.getGraphics();
        g.setColor(Color.orange);
        Font f = new Font(Font.SANS_SERIF, Font.BOLD, 35);
        g.setFont(f);
        g.drawString("ENHORABUENA, EL GANADOR ES EL CICLISTA [" + id + "]", 200, 125);
    }

    // _______________ Gets & Sets ___________________ //
    public int getID() {
        return jComboBoxIDCiclista.getSelectedIndex();
    }

    public int getPinon() {
        return (int) jSpinnerPinones.getValue();
    }

    public int getPlato() {
        return (int) jSpinnerPlatos.getValue();
    }

    public int getCadencia() {
        return (int) jSpinnerCadencia.getValue();
    }

    public double getPeriodo() {
        return (double) jSpinnerPeriodo.getValue();
    }

    public int getIntensidadFrenada() {
        return (int) jSliderIntensidadFrenada.getValue();
    }

    public int getDuracionFrenada() {
        return (int) jSliderDuracionFrenada.getValue();
    }

    public void setPinon(int pinon) {
        jSpinnerPinones.setValue(pinon);
    }

    public void setPlato(int plato) {
        jSpinnerPlatos.setValue(plato);
    }

    public void setCadencia(int cadencia) {
        jSpinnerCadencia.setValue(cadencia);
    }

    public void setPeriodo(double periodo) {
        jSpinnerPeriodo.setValue(periodo);
    }

    public void borrarComando() {
        jTextFieldComandos.setText(null);
    }

    /**
     * Actualiza los valores de las etiquetas del panel
     */
    public void updateLabels(int id) {

        DecimalFormat f = new DecimalFormat("#.###");

        jLabelVelocidad.setText(f.format(ciclistas.get(id).getVelocidad()) + " m/s");
        jLabelFuerza.setText(f.format(((ciclistas.get(id).getFuerzaCiclista() * 100) / Constantes.FUERZA_CICLISTA)) + " %");
        jLabelEspacioRecorrido.setText(f.format(ciclistas.get(id).getBici().getDistanciaRecorrida()) + " m");

        jLabelVelocidadViento.setText(ciclistas.get(id).getVelocidadVientoActual() + " m/s");
        jLabelPendiente.setText(ciclistas.get(id).getPendienteActual() + " %");

        jLabelRelojSistema.setText(getTiempoRealDelSistema());


        jLabelRelojAplicacion.setText(Reloj.getInstanciaDelReloj().getTiempoAplicacion());

        jSpinnerCadencia.setValue(ciclistas.get(id).getCadencia());
        jSpinnerPeriodo.setValue(ciclistas.get(id).getTiempoEnDarLaPedalada());
        jSpinnerPinones.setValue(ciclistas.get(id).getBici().getPinon() + 1);
        jSpinnerPlatos.setValue(ciclistas.get(id).getBici().getPlato() + 1);

        jTextAreaLoggin.setText(Logger.getInstanciaLogger().getMensajes());

    }

    /**
     * Devuelve un string para poder mostrar el tiempo del sistema
     *
     * Codigo obtenido de la pagina web stackOverflow
     *
     * @return el tiempo del sistema en formato reloj digital
     */
    private String getTiempoRealDelSistema() {

        String ceroSegundos = "";
        String ceroMinutos = "";

        Calendar relojDelSistema = Calendar.getInstance();

        if (relojDelSistema.get(Calendar.MINUTE) < 10) {
            ceroMinutos = "0";
        }
        if (relojDelSistema.get(Calendar.SECOND) < 10) {
            ceroSegundos = "0";
        }

        String am_pm;

        if (relojDelSistema.get(Calendar.AM_PM) == 0) {
            am_pm = " a.m";
        } else {
            am_pm = " p.m";
        }

        String reloj = relojDelSistema.get(Calendar.HOUR) + ":" + ceroMinutos + relojDelSistema.get(Calendar.MINUTE) + ":" + ceroSegundos + relojDelSistema.get(Calendar.SECOND) + ":" + relojDelSistema.get(Calendar.MILLISECOND) / 100 + am_pm;
        return reloj;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFrenar;
    private javax.swing.JComboBox jComboBoxIDCiclista;
    private javax.swing.JLabel jLabelCadenciaTxt;
    private javax.swing.JLabel jLabelCiclistaTxt;
    private javax.swing.JLabel jLabelCiclistasTxt;
    private javax.swing.JLabel jLabelComandosTxt;
    private javax.swing.JLabel jLabelConfirmacionTxt;
    private javax.swing.JLabel jLabelDuracionFrenadaTxt;
    private javax.swing.JLabel jLabelEspacioRecorrido;
    private javax.swing.JLabel jLabelEspacioRecorridoTxt;
    private javax.swing.JLabel jLabelFactoresTxt;
    private javax.swing.JLabel jLabelFuerza;
    private javax.swing.JLabel jLabelFuerzaTxt;
    private javax.swing.JLabel jLabelIntensidadFrenadaTxt;
    private javax.swing.JLabel jLabelLogginTxt;
    private javax.swing.JLabel jLabelPendiente;
    private javax.swing.JLabel jLabelPendienteTxt;
    private javax.swing.JLabel jLabelPeriodoTxt;
    private javax.swing.JLabel jLabelPinonesTxt;
    private javax.swing.JLabel jLabelPlatosTxt;
    private javax.swing.JLabel jLabelRelojAplicacion;
    private javax.swing.JLabel jLabelRelojAplicacionTxt;
    private javax.swing.JLabel jLabelRelojSistema;
    private javax.swing.JLabel jLabelRelojSistemaTxt;
    private javax.swing.JLabel jLabelVelocidad;
    private javax.swing.JLabel jLabelVelocidadTxt;
    private javax.swing.JLabel jLabelVelocidadViento;
    private javax.swing.JLabel jLabelVelocidadVientoTxt;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelCarreraFondo;
    private javax.swing.JPanel jPanelIndicadores;
    private javax.swing.JPanel jPanelLoggin;
    private javax.swing.JScrollPane jScrollPaneCarreraFondo;
    private javax.swing.JScrollPane jScrollPaneLoggin;
    private javax.swing.JSlider jSliderDuracionFrenada;
    private javax.swing.JSlider jSliderIntensidadFrenada;
    private javax.swing.JSpinner jSpinnerCadencia;
    private javax.swing.JSpinner jSpinnerPeriodo;
    private javax.swing.JSpinner jSpinnerPinones;
    private javax.swing.JSpinner jSpinnerPlatos;
    private javax.swing.JTextArea jTextAreaLoggin;
    private javax.swing.JTextField jTextFieldComandos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ejecutar() {
        this.updateLabels(this.getID());

        if (contenedor.getCurvas().getActualizado()) {

            ImageIcon img = new ImageIcon("img/curve.gif");

            jPanelCarreraFondo.add(new JLabel(img));
            jPanelCarreraFondo.getComponent(contenedor.getCurvas().getNumCurvas() - 1).setSize(20, 17);
            jPanelCarreraFondo.getComponent(contenedor.getCurvas().getNumCurvas() - 1).setVisible(true);
            panelCarrera.pintarCurvas(jPanelCarreraFondo);
        }

        if (contenedor.getPendiolo().getActualizado()) {
            panelCarrera = new PanelCarrera(contenedor);
            jPanelCarreraFondo = panelCarrera.getJPanel();

            ImageIcon img = new ImageIcon("img/meta.png");

            jPanelCarreraFondo.add(new JLabel(img));
            jPanelCarreraFondo.getComponent(0).setSize(50, 100);
            jPanelCarreraFondo.getComponent(0).setVisible(true);

            for (int i = 1; i < contenedor.getCurvas().getNumCurvas() + 1; i++) {

                img = new ImageIcon("img/curve.gif");
                jPanelCarreraFondo.add(new JLabel(img));
                jPanelCarreraFondo.getComponent(i).setSize(20, 17);
                jPanelCarreraFondo.getComponent(i).setVisible(true);
            }

            jScrollPaneCarreraFondo.setViewportView(jPanelCarreraFondo);
        }

        panelCarrera.pintarCurvas(jPanelCarreraFondo);
        panelCarrera.pintarCiclistas(jPanelCarreraFondo);

    }
}
